info:
  contact: {}
  description: 基于client-go和gin框架后端api服务
  termsOfService: https://github.com/sreok/kube-go
  title: kube-go
  version: 0.1.0
paths:
  /api/namespaces:
    get:
      description: 获取命名空间
      responses: {}
      summary: 获取命名空间
      tags:
      - Kubernetes
  /api/pods:
    get:
      description: 获取pod列表
      responses: {}
      summary: 获取pod列表
      tags:
      - Kubernetes
swagger: "2.0"
