apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: kube-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeOperator
rules:
  - apiGroups: [""]
    resources: ["pods","deployments","namespaces"]
    verbs: ["get", "watch", "list","create","delete","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeServiceAccount-kubeOperator
roleRef:
  kind: ClusterRole
  name: kubeOperator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kube-sa
    namespace: default