info:
  contact: {}
  description: 基于client-go和gin框架后端api服务
  termsOfService: https://github.com/sreok/kube-go
  title: kube-go
  version: 0.1.0
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      produces:
      - application/json
      responses: {}
      summary: Show an account
      tags:
      - 获取命名空间
swagger: "2.0"
